[functions]
  external_node_modules = ["express", "dotenv", "jsonwebtoken", "bcryptjs", "mongoose", "mongoose-unique-validator"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
